name: Deploy Backend (Manual)

on:
  workflow_dispatch:   # 👈 hanya manual

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Login GHCR
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io \
            -u ${{ github.actor }} --password-stdin

      - name: Build & Push Image
        run: |
          docker build -t ghcr.io/${{ github.actor }}/presensi-kpu-batu-be:latest ./presensi-kpu-batu-be
          docker push ghcr.io/${{ github.actor }}/presensi-kpu-batu-be:latest

      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: root
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd /opt/presensi
            docker-compose pull backend
            docker-compose up -d backend
